version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # This is a base image for running Docker commands.
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7  # Docker version to use
          docker_layer_caching: true  # Enable caching for faster builds
      - run:
          name: Set up Docker Hub credentials
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t prayags/nodejs-app .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push prayags/nodejs-app:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
