version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # This is a base image for running Docker commands.
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true  # Enable caching for faster builds
      - run:
          name: Set up Docker Hub credentials
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t prayags/node-app1 .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push prayags/node-app1:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
